ignore:
  - 'src/reportWebVitals.ts'
  - 'src/index.tsx'
  - 'src/setupTests.ts'
  - 'src/react-app-env.d.ts'
  - '**/*.json'
  - '**/node_modules/'
  - '**/coverage/'
  - 'src/models/graphql/**'
  - 'src/testdata/**'
  - 'src/graphql/client.ts'
